### ISSUE TITLE
staff tags feature request 

### ISSUE THREAD

**Issue by SL4F** [revenge-mod/addon-requests#18]
### Discord username

sl4f

### Plugin description

follow theme for the tags setting, and ability to customise the text for the tags 
https://vd-plugins.github.io/proxy/fierdetta.github.io/staff-tags/

### Rules

- [X] I have read the README and checked this wasn't already suggested

**Comment by Angelix1** [comment]
I'll Try refactor the code to my liking, so yea, and i'll add customization for the Text and Color of the tags, no promises tho

**Comment by Angelix1** [comment]
Chek Plugins forum in discord server to see further, and here's the instal link 
https://angelix1.github.io/MP/vendetta/customtags

**Comment by nexpid** [comment]
@Angelix1 follow the claiming protocol next time

**Comment by SL4F** [comment]
thank you so much :)
