### ISSUE TITLE
Change the avatar of a bot/someone else locally

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revenge-mod/addon-requests#24]
### Plugin description

A plugin that changes the pfp of some bot/user locally. Maybe because two bot/user have the same/similar avatar. Or that the bot avatar is ugly and you want to change it.

### Elaborate

Because you cannot change the pfp of a bot with userpfp. 

### Rules

- [X] I have read the README and checked this wasn't already suggested

**Comment by Angelix1** [comment]
before i claim this, i want ask for further elaboration, does the PFP need to shown in the `Profile View, Member List, DM List, Chat Rows, Detailed Profile Views` or just `Chat Rows` or `Chat rows` and `Profile View` (similiar to `USERPFP`)?

**Comment by Angelix1** [comment]
I'll claim this and while waiting for the respond, i'll work the core of it

**Comment by SodaWithoutSparkles** [comment]
I dont quite understand the technical layout terms so I'll provide screenshots as examples.

![Screenshot_2024-03-25-08-31-33-266_dev.beefers.vendetta-edit.jpg](https://github.com/revenge-mod/addon-requests/assets/64138578/b9d7f4ca-bcc3-4e20-9f30-8ab53621d43e)

![Screenshot_2024-03-25-08-30-47-401_dev.beefers.vendetta-edit.jpg](https://github.com/revenge-mod/addon-requests/assets/64138578/8367be17-404b-485b-b412-c665b1777b3b)

![Screenshot_2024-03-25-08-30-03-137_dev.beefers.vendetta-edit.jpg](https://github.com/revenge-mod/addon-requests/assets/64138578/6054deda-e7ce-44c5-8f25-246b8d034b32)

**Comment by Angelix1** [comment]
Published v1.0.0
> Install: https://angelix1.github.io/MP/vendetta/fakeavatars
> Source: https://github.com/Angelix1/MP/tree/master/vendetta/fakeavatars

**Comment by SodaWithoutSparkles** [comment]
Thanks @Angelix1 ! The plugin works mostly as expected. 

There's one minor bug tho. 

------
## Expected 

The overridden avatar override the original avatar at all times.

## Actual 

The replaced image does not apply on first load. 

## Steps to reproduce 

1. Override some bot's avatar
2. Go back and verify that the avatar was overridden
3. Dont leave the channel, close ReVenge / Vendetta 
4. Launch ReVenge / Vendetta again, you should have landed on the same channel
5. Verify that the avatar did not get overridden  <-- issue
6. Visit another channel and go back to the last one
7. Avatar was overridden as expected

**Comment by Angelix1** [comment]
that's just quirk inherited from userpfp, not sure how to fix, cuz my assumption is vendetta/revenge loaded/patch after all stuff discord stuff finished loaded to avoid crash or patching a non-existence functions

**Comment by SodaWithoutSparkles** [comment]
Fair enough. 

This issue can probably be closed now
