### ISSUE TITLE
Cloud Sync issue in v221.16

### ISSUE THREAD

**Issue by BedBug2479** [revenge-mod/addon-requests#25]
### Plugin description

After importing the files from cloud sync it shows an error and tells you to restart.

After doing restart it just gets stuck in Loading screen

### Elaborate

After importing the files from cloud sync it shows an error and tells you to restart.

After doing restart it just gets stuck in Loading screen

### Rules

- [X] I have read the README and checked this wasn't already suggested

**Comment by riivx** [comment]
in the plugin repo, not in requests 😭😭
https://github.com/nexpid/RevengePlugins
