### ISSUE TITLE
Fix the broken and unmaintained reverse image search plugin

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revenge-mod/addon-requests#4]
### Discord username

@SodaWithoutSparkles

### Plugin description

Fix the now broken and no-longer maintained plugin by redstonekasi at 
https://vd-plugins.github.io/proxy/redstonekasi.github.io/vendetta-plugins/saucenao/

### Elaborate

[](url)The issue is that the URL isnt properly URL-encoded.

For example, a pic can have a URL of: https://cdn.discordapp.com/attachments/1109213245060943944/1213861690849103882/azumanga-daioh-azumanga.gif?ex=65f703cb&is=65e48ecb&hm=fe45f59b8e2a6907ccdb5b54e9eb3ba334b0befc6b5e848419d4d74852ed797b&

But the plugin returns a address URL of: 
https://saucenao.com/search.php?url=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F1109213245060943944%2F1213861690849103882%2Fazumanga-daioh-azumanga.gif%3Fex%3D65f703cb&is=65e48ecb&hm=fe45f59b8e2a6907ccdb5b54e9eb3ba334b0befc6b5e848419d4d74852ed797b

This caused an error of: 
```Specified file no longer exists on the remote server! (404 - https://cdn.discordapp.com/attachments/1109213245060943944/1213861690849103882/azumanga-daioh-azumanga.gif?ex=65f703cb)```

Solution is to URL-encode the symbols properly, especially the `&`. After a proper URL-encode it works normally:
https://saucenao.com/search.php?url=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F1109213245060943944%2F1213861690849103882%2Fazumanga-daioh-azumanga.gif%3Fex%3D65f703cb%26is%3D65e48ecb%26hm%3Dfe45f59b8e2a6907ccdb5b54e9eb3ba334b0befc6b5e848419d4d74852ed797b%26

### Rules

- [X] I have read the README and checked this wasn't already suggested

**Comment by SodaWithoutSparkles** [comment]
Orginal code can be found [here](https://github.com/redstonekasi/vendetta-plugins/blob/main/plugins/saucenao/src/index.tsx) 

The reason for thinking it was "unmaintained" is that the README doesnt even update/contain the plugin

**Comment by Angelix1** [comment]
i could forked the repo and reupload it with update, but i need to ask kasi first

**Comment by SodaWithoutSparkles** [comment]
> i could forked the repo and reupload it with update, but i need to ask kasi first

I thought the BSD 3-clause license allows this?

**Comment by Angelix1** [comment]
Idk man, i dont understand LICENSE lol

**Comment by nexpid** [comment]
we're working on an 'official' Revenge monorepo that would house fixed forks of unmaintained Vendetta plugins
no more details for now, though, so stay tuned for that

**Comment by Angelix1** [comment]
For now i updated the thing and renamed it to RIS and added one additional services, 
here's the install link https://angelix1.github.io/MP/vendetta/ris
